app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns+=[
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from goods import views
app_name = 'goods'
urlpatterns = [

    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),

]

main/urls.py
from django.urls import path
from main import views
app_name='main'
urlpatterns = [

    path('',views.index,name='index'),
    path('about/', views.about, name='about'),

]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

goods/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="goods_images", blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'

    def display_id(self):
        return f"{self.id:05}"

    def total_price(self):
        if self.discount:
            return round(self.price-self.price*self.discount/100,2)
        return self.price

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    image: models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Avatar')

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'password']




class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ( 'first_name', 'last_name', 'username', 'email', 'password1', 'password2')

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email"
        )

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from goods.models import Product
from goods.utils import q_search


# Create your views here.
def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == 'vse-tovary':
        goods = Product.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = Product.objects.filter(category__slug=category_slug)
    if on_sale:
        goods = goods.filter(discount__gt=0)
    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))
    context: dict[str, any] = {
        'title': 'Home - Каталог',
        'goods': current_page,
        'slug_url':category_slug
    }
    return render(request,'goods/catalog.html', context)

def product(request, product_slug):
    product = Product.objects.get(slug=product_slug)

    context ={
        'product': product
    }
    return render(request, 'goods/product.html', context=context)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from goods.models import Category

def index(request):
    context: dict[str,str]={
        'title' : 'Home - Главная',
        'content' : 'Магазин мебели HOME',
    }

    return render(request,'main/index.html',context)
def about(request):
    context: dict[str, str] = {
        'title': 'Home - О нас',
        'content': 'О нас',
        'text_on_page':"sdfs adsdssad adasasdasdad dsadad"
    }

    return render(request, 'main/about.html', context)

users/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm


# Create your views here.
def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Home - LogIn',
        'form': form
    }
    return render(request, 'users/login.html', context)
def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():

            form.save()
            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'Home - Registration',
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'title': 'Home - Profile',
        'form': form
    }
    return render(request, 'users/profile.html', context)
@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main:index"))

main/templates/main/about.html
{% extends "base.html" %}
{% load static %}
 {% block css%}
     <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
 {% endblock %}
{% block content %}
                    <h2 class="mt-5 pt-5"><strong>{{ content }}</strong></h2>
    <p>{{  text_on_page}}</p>
{% endblock %}
{% block footer %}
<footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}
 {% block css%}
     <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
 {% endblock %}
{% block content %}
                    <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock %}
{% block footer %}
<footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock %}

templates/base.html
{% load static %}
{% load goods_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    {% block css%}
    {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:login" %}">Войти</a>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'user:profile' %}">Личный кабинет</a>
                                </li>
                                {% if user.is_admin or user.is_staff %}
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url 'user:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search"  action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                             height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                    {% tag_categories as categories %}
                        {% for category in categories %}
                        <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug%}">{{ category.name }}</a></li>
                        {% endfor %}
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                             height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="deps/icons/trash3-fill.svg"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content%}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer%}
    {% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
                        <div class="container mt-5">
                            <div class="row">
                                <!-- Профиль с данными пользователя -->
                                <div class="col-md-5">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                                        <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12 mb-3 text-center">
                                                    <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                        style="max-width: 150px;">
                                                    <input type="file" class="form-control mt-3" id="id_image"
                                                           name="image"
                                                        accept="image/*">
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="firstName" class="form-label">Имя*</label>
                                                    <input type="text" class="form-control" id="id_first_name"
                                                           name="first_name"
                                                        placeholder="Введите ваше имя"
                                                           value="{{ form.first_name.value }}"
                                                           required>
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="lastName" class="form-label">Фамилия*</label>
                                                    <input type="text" class="form-control" id="id_last_name"
                                                           name="last_name"
                                                        placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="username" class="form-label">Имя пользователя*</label>
                                                    <input type="text" class="form-control" id="id_username"
                                                           name="username"
                                                        placeholder="Введите ваше имя пользователя" value="{{ form.username.value }}" required>
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="email" class="form-label">Email*</label>
                                                    <input type="email" class="form-control" id="id_email" name="email"
                                                        placeholder="Введите ваш email *youremail@example.com" value="{{ form.email.value }}"
                                                        required>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-dark">Сохранить</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- Корзина -->

                                            <!-- Закончилась разметка корзины -->
                                        </div>
                                        <a class="btn btn-dark" href="../orders/create_order.html">
                                            Оформить заказ
                                        </a>
                                    </div>
                                </div>
                                <!-- Оформленные заказы -->
                                <div class="col-md-12">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Мои заказы</h3>
                                        <!-- Разметка заказов -->
                                        <div class="container">
                                            <div class="accordion" id="accordionExample">
                                                <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading1">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                                            Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-dark table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Товар</th>
                                                                        <th>Количество</th>
                                                                        <th>Цена</th>
                                                                        <th>Общая стоимость</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                                        <td>1</td>
                                                                        <td>255.00 $</td>
                                                                        <td>255.00 $</td>

                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                            <div class="d-flex justify-content-between">
                                                                <p><strong>Итого:</strong></p>
                                                                <p><strong>255.00 $</strong></p>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading2">
                                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                                            Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-dark table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Товар</th>
                                                                        <th>Количество</th>
                                                                        <th>Цена</th>
                                                                        <th>Общая стоимость</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <td><a class="text-white" href="#">Стул офисный</a></td>
                                                                        <td>2</td>
                                                                        <td>30.00 $</td>
                                                                        <td>60.00 $</td>

                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Закончилась разметка заказов -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}